baseURL = "https://cyphai.io"
languageCode = "en-us"
DefaultContentLanguage = "en"
hasCJKLanguage = true
title = "CyPhAI Project"
author = "CyPhAI Project"
theme = "hugo-flex"
copyright = "Copyright notice and date: © CyPhAI Project, 2021-2024."

[params]
  color = "#2980b9"
  footer = "Copyright notice and date: © CyPhAI Project, 2021-2024."
  favicon = true
  divider = "\\2500\\2500\\2500"
  toc = false # Disable Table of Contents
  width = "75%"
  css = [ "css/styles.css" ]

# The header
[menu]
  [[menu.main]]
    name = "Members"
    url = "members/"
    weight = 10
  [[menu.main]]
    name = "Open Positions"
    url = "open-positions/"
    weight = 20

[markup]
  [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true
